# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 星辰阁
subtitle: 不积跬步无以至千里 不积小流无以成江河
description: Java技术分享 技术探索 代码设计
keywords: Java MySQL spring mybatis Redis 缓存 nosql jdk jdk17
author: 西门敬雪
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://chenyaoboy.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
#资源文件夹，这个文件夹用来存放内容
source_dir: source
#公共文件夹，这个文件夹用于存放生成的站点文件
public_dir: public
#标签文件夹
tag_dir: tags
#存档文件夹
archive_dir: archives
#分类文件夹
category_dir: categories
#Include code 文件夹，source_dir 下的子目录
code_dir: downloads/code
#国际化（i18n）文件夹
i18n_dir: :lang
#跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。
#举例
##skip_render: "mypage/**/*"
## 将会直接将 `source/mypage/index.html` 和 `source/mypage/code.js` 不做改动地输出到 'public' 目录
## 你也可以用这种方法来跳过对指定文章文件的渲染
#skip_render: "_posts/test-post.md"
## 这将会忽略对 'test-post.md' 的渲染
skip_render:

# Writing
#新文章的文件名称
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post #预设布局
titlecase: false #把标题转换为 title case
external_link:
  enable: true # 在新标签中打开链接
  field: site #对整个网站（site）生效或仅对文章（post）生效
  exclude: '' #需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #显示草稿
post_asset_folder: true #启动 Asset 文件夹
relative_link: false #把链接改为与根目录的相对位址
future: true #显示未来的文章
highlight: #代码块的设置, 请参考 Highlight.js 进行设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs: #代码块的设置, 请参考 PrismJS 进行设置
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 	默认分类
default_category: java
category_map: #分类别名
tag_map: #标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page #分页目录

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
#Hexo 默认会不包括 source/ 下的文件和文件夹（包括名称以下划线和 . 开头的文件和文件夹，Hexo 的 _posts 和 _data 等目录除外）。
#通过设置此字段将使 Hexo 处理他们并将它们复制到 source 目录下。
include:
#Hexo 不包括 source/ 下的这些文件和目录
exclude:
#Hexo 会忽略整个 Hexo 项目下的这些文件夹或文件
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly #当前主题名称。值为false时禁用主题

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
#部署部分的设置
deploy:
  type: git
  repo: https://github.com/chenyaoBOY/chenyaoBOY.GitHub.io.git
  branch: master
